version: '3.7'
services:
  cast_service:
    image: ${DOCKER_ID}/${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: cast_service
    networks:
      - my_network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
networks:
  my_network:
    external: true
